name: Deploy to Azure App Service

# Trigger deployment on push to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests (optional)
      run: |
        # Add your test commands here
        python -c "import app; print('App imports successfully')"
    
    - name: Create deployment package
      run: |
        zip -r deployment.zip . -x "*.git*" "__pycache__/*" "*.pyc" "venv/*" ".env"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-app
        path: deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: python-app
    
    - name: Extract deployment package
      run: unzip deployment.zip
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nestle-chatbot-app'  # Replace with your app name
        slot-name: 'production'
        package: '.'
    
    - name: Azure CLI script (Post-deployment)
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          # Restart the app service to ensure new deployment is loaded
          az webapp restart --name nestle-chatbot-app --resource-group nestle-chatbot-rg